name: govee-h5075-prom-exporter-amd64

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "main"
    paths-ignore:
      - 'README.md'
      - 'LICENSE.md'
      - '.gitignore'
      - '.github/workflows/*'
      - '.known_govees'
      - 'docker-compose.yml'
      - 'mock_server.py'
  push:
    branches:
      - "main"
    paths-ignore:
      - 'README.md'
      - 'LICENSE.md'
      - '.gitignore'
      - '.github/workflows/*'
      - '.known_govees'
      - 'docker-compose.yml'
      - 'mock_server.py'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24.0'
      - name: Run tests
        run: go test -v ./...

  build-and-push:
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: "${{ github.server_url }}/${{ github.repository }}.git#${{ github.ref }}"
          tags: |
            ${{ secrets.DOCKERHUB_SLUG }}/govee-h5075-prom-exporter:amd64-latest
            ${{ secrets.DOCKERHUB_SLUG }}/govee-h5075-prom-exporter:amd64-${{github.run_number}}
